### ISSUE TITLE
Explore options to automatically deploy apps and custom settings

### ISSUE THREAD

**Issue by outcoldman** [outcoldman/docker-splunk-cluster#2]
Splunk container might have an option `INIT_SPLUNK_CUSTOM_OVERRIDE=/opt/my-custom-splunk`, so user will be able to override docker-compose with

```
version: '2'
services:

  shc-deployer:
    environment: 
      - INIT_SPLUNK_CUSTOM_OVERRIDE=/opt/my-custom-splunk
    volumes:
      - shc-deployer-custom-volume:/opt/my-custom-splunk

volumes:
  shc-deployer-custom-volume:
```

If `shc-deployer-custom-volume` will have something in `etc/shcluster/apps` - image will copy everything over splunk location which will trigger installation of this apps, when SHC will be bootstrapped.
